### ISSUE TITLE
Certificate template assignment to enterprise CAs

### ISSUE THREAD

**Issue by Crypt32** [GoateePFE/ADCSTemplate#2]
Your .psm1 file contains the following code that assigns imported/generated certificate template to all enterprise CAs in the forest. However, the relevant code part contains this line:

```PowerShell
Set-ADObject -Identity $CA.DistinguishedName -Add @{certificateTemplates=$DisplayName} -Server $Server
```
Certificate templates are referenced by common name (CN attribute), not by `DisplayName` attribute.

**Comment by GoateePFE** [comment]
Fixed in 1.0.1.0. Also fixed in other functions within the module.
